# fly.toml file generated for cenph on 2023-04-14T17:55:30+05:00

app = "cenph"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "sin"

[env]
API_URL = "http://cenph.internal:8080"
DATABASE_URL = "file:/data/sqlite.db"
PORT = "8080"
PRIMARY_REGION = "sin"

[mounts]
processes = ["web"]
source = "data"
destination = "/data"

[processes]
cenph-reminder = "/app/cenph-reminder/cenph-reminder"
web = "/app/start_with_migrations.sh"

[[services]]
protocol = "tcp"
internal_port = 8080
processes = ["web"]

[[services.ports]]
port = 80
handlers = ["http"]
force_https = true

[[services.ports]]
port = 443
handlers = ["tls", "http"]
[services.concurrency]
type = "connections"
hard_limit = 25
soft_limit = 20

[[services.tcp_checks]]
interval = "5s"
timeout = "2s"
grace_period = "1m0s"
restart_limit = 0

[[services.http_checks]]
interval = "10s"
timeout = "5s"
grace_period = "1m0s"
restart_limit = 0
method = "get"
path = "/"
protocol = "http"

[[services]]
restart_limit = 1
processes = ["cenph-reminder"]
